name: VADR
favicon: null
layout_spectrum: 0.75848
typography_spectrum: 0.4317157007753849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6726660116109997
  lightness: 0.5122643117792904
  saturation: 0.5831109932623804
  rhythmicContrast: 0.11753564467653632
purpose: []
